PostLikeTag 리소스 API 구현 및 API 문서 추가
FirstianB101/reciptopia-server pull request #115
Opened 2022-04-12 13:56 UTC by KimSilverStar

커밋 내용과 같음

2022-04-13 04:58 UTC, tellang requested changes

2022-04-13 04:58 UTC, tellang commented on src/main/java/kr/reciptopia/reciptopiaserver/domain/model/PostLikeTag.java
> +				.withId(id);
with가 Post는 만들어줄것같은데?

2022-04-13 04:58 UTC, tellang commented on src/main/java/kr/reciptopia/reciptopiaserver/business/service/PostLikeTagService.java
> +    }
사실 `LikeTag`에 필터링(specification)이 필요할까 싶다.
이 문제를 `SearchHistory`에서도 생각했었는데, `SearchHistory`는 조건 검색이 필요하지 않다고 판단하여 현재 paging만 작동하도록 만든상태임.

`LikeTag`도 이에 대해 좀 더 생각해봐야할 문제라고 생각함

2022-04-13 04:58 UTC, tellang commented on src/main/java/kr/reciptopia/reciptopiaserver/controller/PostLikeTagController.java
> +	}
현재 그러면 `LikeTag`를 모두 조회하는 URL이 없어 보이는데,
커밋내용에 없어서 혹시나 해서 적어봄

2022-04-13 04:58 UTC, tellang commented on src/main/java/kr/reciptopia/reciptopiaserver/business/service/helper/RepositoryHelper.java
> +
사실 커밋할때 죄다 붙어있어서 귀찮긴한데
그래도 따로 떼서 올려주는게 추후에 커밋을 되돌리거나, 추적할때 
발생할 수 있는 비용을 줄여주는 방식이라고 생각함

2022-04-13 04:58 UTC, tellang commented on src/main/java/kr/reciptopia/reciptopiaserver/business/service/authorizer/LikeTagAuthorizer.java
> +            throw errorHelper.forbidden("Not the owner of the likeTag");
무슨 `LikeTag`인지 까지는 써 주는게 나중에 로그볼때 덜 빡칠듯

2022-04-13 04:58 UTC, tellang commented on src/docs/asciidoc/api-guide.adoc
> -v0.8.0-alpha 변경사항
0.9.0은 `SearchHistory`추가였습니다

2022-04-13 04:59 UTC, tellang commented on src/main/java/kr/reciptopia/reciptopiaserver/business/service/helper/RepositoryHelper.java
> +
지금은 그냥 넘어가져

2022-04-13 05:02 UTC, KimSilverStar commented on src/main/java/kr/reciptopia/reciptopiaserver/business/service/authorizer/LikeTagAuthorizer.java
> +            throw errorHelper.forbidden("Not the owner of the likeTag");
ㅇㅎ post 붙은거 앞에 떼다가 얘까지 지워버린듯

2022-04-13 06:10 UTC, tellang commented on src/test/java/kr/reciptopia/reciptopiaserver/PostLikeTagIntegrationTest.java
> +            assertThat(repository.findById(id)).isEmpty();
아 이거 템플릿 여기 뺴먹나보네
existsById()).isFalse()가 좀 더 적절해서 해당 구문으로 바꿀 예정

2022-04-13 06:23 UTC, KimSilverStar commented on src/main/java/kr/reciptopia/reciptopiaserver/domain/model/PostLikeTag.java
> +				.withId(id);
상속 관계 클래스의 필드에 대해서 통일된 with 적용이 안되는 듯 함.

- 부모 클래스 LikeTag의 필드 Account owner
- 자식 클래스 PostLikeTag의 필드 Post post

PostLikeTag 클래스에 With 어노테이션을 추가 후,
직접 재정의한 withPost() 메소드를 주석처리하면 withOwner() 가 정상적으로 작동하지 않음 (owner 필드가 채워지지 않고, null이 됨)

2022-04-13 06:27 UTC, KimSilverStar commented on src/main/java/kr/reciptopia/reciptopiaserver/business/service/helper/RepositoryHelper.java
> +
각 세부 LikeTag 구현할 때, 따로 커밋 올렸어야했는데 깜빡하고 같이 올려버린 것 같음

2022-04-13 06:28 UTC, KimSilverStar commented on src/main/java/kr/reciptopia/reciptopiaserver/business/service/PostLikeTagService.java
> +    }
PostLikeTag를 누른 Account 별, 또는 Post 별로 검색 할 이유가 혹시 있나 ㅇ?

2022-04-13 06:48 UTC, tellang commented on src/main/java/kr/reciptopia/reciptopiaserver/business/service/PostLikeTagService.java
> +    }
그러면 Account에서 PostLikeTag, Post에서 PostLikeTag를 알 필요가 없네?

2022-04-13 07:02 UTC, KimSilverStar commented on src/main/java/kr/reciptopia/reciptopiaserver/business/service/PostLikeTagService.java
> +    }
`Account`, `Post` 엔티티에 각각 `Set<PostLikeTag>` 필드가 있으니,
`PostLikeTag`의 조건 검색 기능은 불필요 할 것으로 보임.

2022-04-13 07:16 UTC, KimSilverStar commented on src/main/java/kr/reciptopia/reciptopiaserver/controller/PostLikeTagController.java
> +	}
처음에 생각했던게 전체 `PostLikeTag` 조회 기능이 필요 없다고 생각했음.
`Account`  or `Post` 단위로 해당 사용자가 누른 좋아요, 해당 게시물에 붙은 좋아요들을 조회하는 게 필요할 것 같아서
따로 전체 `PostLikeTag` 조회를 만들지 않았음.

그런데 다시 생각해보니 위 이전 댓글을 보고, 전체 `PostLikeTag` 조회 기능을 추가하고,
`Account`, `Post` 별 조건 검색 기능을 빼는 것이 맞을 것 같음.

2022-04-14 03:19 UTC, tellang requested changes

2022-04-14 03:19 UTC, tellang commented on src/docs/asciidoc/api-guide.adoc
> -=== PostLikeTag 삭제
서는 뭔데

2022-04-14 03:20 UTC, tellang commented on src/docs/asciidoc/api-guide.adoc
> +=== PostLikeTag 삭제서
서는 뭔데

2022-04-14 04:42 UTC, tellang approved these changes

2022-04-14 04:53 UTC, merged