PostImg API 추가
FirstianB101/reciptopia-server pull request #173
Opened 2022-06-06 05:42 UTC by KimSilverStar

커밋 내용과 같음

2022-06-06 06:46 UTC, tellang requested changes

2022-06-06 06:46 UTC, tellang commented on src/main/java/kr/reciptopia/reciptopiaserver/business/service/PostImgService.java
> +		}
만약에 서버에서 image가 하나 유실되어서 반드시 하나를 찾을 수 없다면 그 postImage객체는 지울 수 없는건가

2022-06-06 06:46 UTC, tellang commented on src/main/java/kr/reciptopia/reciptopiaserver/business/service/PostImgService.java
> +		postImgRepository.deleteAllInBatch(postImgList);
put이라는 역할을 하는 하나의 메소드에서 너무 많은 로직이 구현되어 있는게 아닐까 함
그래서 하나의 특징적인 세부 기능들은 하나의 메소드로 분리하는것도 좋을것같다.

2022-06-06 06:50 UTC, KimSilverStar commented on src/main/java/kr/reciptopia/reciptopiaserver/business/service/PostImgService.java
> +		}
PostImg 실제 이미지 파일 리소스를 찾지 못했을 때,
예외 처리 로직을 좀더 고민 해봐야될듯

2022-06-07 03:14 UTC, tellang approved these changes

2022-06-07 03:14 UTC, merged