Comment 리소스 API 구현 및 API 문서 추가
FirstianB101/reciptopia-server pull request #81
Opened 2022-04-02 08:52 UTC by KimSilverStar

커밋 내용과 같음

2022-04-02 12:48 UTC, tellang requested changes

2022-04-02 12:48 UTC, tellang commented on src/main/java/kr/reciptopia/reciptopiaserver/persistence/repository/CommentRepository.java
> +}
여기서 Comment를 ownerId와, postId로 특정하려 하는데, 
한 사람이 한  Post에 대해 여러개의 Comment를 작성하면 위 쿼리문은 Comment를 특정하지 못해 예외가 발생할 것 같다.

위 메소드의 반환값을 Collection 형식으로 변경하거나 하나의 Comment로 특정할 수 있는 추가적인 매개변수가 필요해 보인다

2022-04-02 12:48 UTC, tellang commented on src/main/java/kr/reciptopia/reciptopiaserver/business/service/CommentService.java
> +    }
사실 생성자가 하나일 경우 @Autowired를 생략 하는것이 가능하다.
이를 응용하면
@RequiredArgsConstructor 애노테이션 하나로 표현하는 방법도 가능하다

2022-04-02 12:48 UTC, tellang commented on src/main/java/kr/reciptopia/reciptopiaserver/business/service/CommentService.java
> +        Post dtoPost = repoHelper.findPostOrThrow(dto.postId());
dtoOwner라는 표현이 어색하다.
마치 dto의 Owner라는 의미로 다가오는데, dto에 owner라는것이 없어서 어색할 뿐더러 
이미 dto가 아닌 entity의 형태의 owner이기 때문에 owner만 적어주는편이 좋지않을까 생각된다.

위와 비슷한 이유로 dtoPost또한 어색하다.
여담으로 "dto`EntityType`" 보다 "`EntityType`dto"의 표현 방법이 `EntityType`의 dto 라는 의미를
좀 더 직관적으로 표현하고 있는것이 아닐까?

2022-04-02 12:48 UTC, tellang commented on src/test/java/kr/reciptopia/reciptopiaserver/CommentIntegrationTest.java
> +    private AuthHelper authHelper;
아ㅋㅋ 숨막혀요

2022-04-02 12:48 UTC, tellang commented on src/main/java/kr/reciptopia/reciptopiaserver/controller/CommentController.java
> +    @PostMapping("/comments")
사실 URL에 대해서 미리 언급했어야 했는데
URL에 대해 말하기전에 REST에 대해 먼저 얘기하는것이 맞다고 생각한다.

비록 지금의 API가 당연히 완벽한 REST라고 말할 수 없고, RESTful하다고 조차 말하기 애매한 부분이 없잖아 존재하지만 그럼에도 불구하고 우리는 RESTful API를 지향하는 방향으로 개발하고 있기때문에 가능한 부분에서 한해 REST함을 
지켜가며 개발하는 방향이 좀 더 좋은 방향이라고 생각한다.

이 좁은칸에 다 쓰는것 보다
아래글을 참고해보는것이 좋을것같다
https://gmlwjd9405.github.io/2018/09/21/rest-and-restful.html

2022-04-03 06:38 UTC, KimSilverStar commented on src/main/java/kr/reciptopia/reciptopiaserver/controller/CommentController.java
> +    @PostMapping("/comments")
댓글을 나타내는 리소스 Comment는 게시물 Post 안에 있다.
즉, 1개의 Post에 다수의 Comments가 존재할 수 있다.
따라서 Restful 하도록 좀더 구조적으로 이해하기 쉽게,
URL을 "/comments" -> "/post/comments" 로 변경하였다.

2022-04-03 06:38 UTC, KimSilverStar commented on src/test/java/kr/reciptopia/reciptopiaserver/CommentIntegrationTest.java
> +    private AuthHelper authHelper;
ㅋㅋ;; 템플릿으로 만들어놓고 엔터 안쳐놨음

2022-04-03 06:38 UTC, KimSilverStar commented on src/main/java/kr/reciptopia/reciptopiaserver/persistence/repository/CommentRepository.java
> +}
List<Comment> findAllByOwnerIdAndPostId() 로 바꿔봤으나,
CommentService에서 해당 기능을 사용하지 않아서 일단 제외하였음.
향후, 필요하면 추가하겠음.

2022-04-03 07:28 UTC, tellang approved these changes

2022-04-03 07:29 UTC, merged

2022-04-05 08:14 UTC, tellang commented
close #9